name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas numpy XlsxWriter streamlit openpyxl pillow
        
    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --name="StreamlitApp" --add-data="analysis.py;." --hidden-import=streamlit --hidden-import=pandas --hidden-import=numpy --hidden-import=xlsxwriter --hidden-import=openpyxl --hidden-import=PIL --hidden-import=streamlit.web.cli launcher.py
        
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/*.exe
        
    - name: Create Release (optional)
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: dist/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}