name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed `
          --add-data "analysis.py;." `
          --hidden-import=streamlit `
          --hidden-import=pandas `
          --hidden-import=numpy `
          --hidden-import=xlsxwriter `
          --hidden-import=streamlit.web.cli `
          --hidden-import=streamlit.runtime.scriptrunner.magic_funcs `
          --hidden-import=streamlit.components.v1 `
          --hidden-import=openpyxl `
          --name "Procesador_de_Archivos" `
          --icon=icon.ico `
          launcher.py
    
    - name: Get version
      id: version
      run: |
        if ("${{ github.event_name }}" -eq "workflow_dispatch") {
          echo "version=${{ github.event.inputs.version }}" >> $env:GITHUB_OUTPUT
        } else {
          $version = "${{ github.ref_name }}" -replace "^v", ""
          echo "version=$version" >> $env:GITHUB_OUTPUT
        }
    
    - name: Rename executable with version
      run: |
        $version = "${{ steps.version.outputs.version }}"
        Rename-Item "dist/Procesador_de_Archivos.exe" "dist/Procesador_de_Archivos_v$version.exe"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable-v${{ steps.version.outputs.version }}
        path: dist/Procesador_de_Archivos_v${{ steps.version.outputs.version }}.exe
    
    - name: Create Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/Procesador_de_Archivos_v${{ steps.version.outputs.version }}.exe
        body: |
          ## 🚀 Release v${{ steps.version.outputs.version }}
          
          ### 📥 Download
          Download the `Procesador_de_Archivos_v${{ steps.version.outputs.version }}.exe` file below.
          
          ### 🛠️ Installation
          1. Download the .exe file
          2. Run it (Windows may show a security warning - click "More info" → "Run anyway")
          3. The app will open in your browser automatically
          
          ### ✨ Features
          - Process Excel and CSV files
          - Generate comprehensive analysis reports
          - Export results to Excel format
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}